# Generated by Django 2.2.15 on 2020-08-14 14:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('image_url', models.CharField(max_length=300)),
                ('instagram_username', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('business_number', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.CharField(choices=[('1', '~ 500k'), ('2', '~ 5M'), ('3', '~ 10M')], max_length=30)),
                ('followers', models.CharField(choices=[('1', '~ 1k'), ('2', '~ 5k'), ('3', '~ 10k'), ('4', '~ 50k'), ('5', '~ 100k'), ('6', '~ 500k'), ('7', '> 1M ')], max_length=30)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('Tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, size=None)),
            ],
        ),
    ]
