# Generated by Django 2.2.15 on 2020-08-14 15:06

import api.randomizer
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.CharField(default=api.randomizer.pkgen, max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image_url', models.CharField(max_length=300)),
                ('instagram_username', models.CharField(max_length=30, unique=True)),
                ('phone_number', models.CharField(max_length=30, unique=True)),
                ('business_number', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('city_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.City')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.CharField(default=api.randomizer.pkgen, max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.CharField(default=api.randomizer.pkgen, max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.CharField(default=api.randomizer.pkgen, max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.CharField(default=api.randomizer.pkgen, max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('price', models.CharField(max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
    ]
